default_session_data_timeout: 0
deployment:
  apiGatewayId: 779cmrwtm2
  endpoints:
    alexaApiEndpointUrlNotRecommendedToUse: https://779cmrwtm2.execute-api.eu-west-3.amazonaws.com/amazonAlexaV1
    googleAssistantApiEndointUrl: https://779cmrwtm2.execute-api.eu-west-3.amazonaws.com/googleAssistantDialogflowV1
    samsungBixbyApiEndointUrl: https://779cmrwtm2.execute-api.eu-west-3.amazonaws.com/samsungBixbyV1
    siriApiEndointUrl: https://779cmrwtm2.execute-api.eu-west-3.amazonaws.com/appleSiriV1
  lambda_name: toto12
  s3_bucket_name: lebucketavecbenoit
messages:
  database_client: dynamodb
  dynamodb:
    region_name: eu-west-3
    table_name: skill_hello-world_messages
  use_database_dynamic_messages: true
sessions_users_data:
  database_client: dynamodb
  dynamodb:
    region_name: eu-west-3
    table_name: skill_hello-world_users-data
